### ISSUE TITLE
fullscreen menu - eerste idee

### ISSUE THREAD

**Issue by Nazneen05x** [Maaike0904/back-to-static-creative-coding#6]
Hey girl,

Je fullscreen menu ziet er echt leuk uit, het geeft echt noordpool vibes. Ik vind je idee die je eerst had veel leuker en meer passen bij je opdracht, omdat het silly is door de kleur en vergrootglas 😊.

**Comment by Maaike0904** [comment]
Ik heb het weer terug gebracht in mijn ontwerp 💪🏼
